# Generated by Django 6.0.2 on 2026-02-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
