# Generated by Django 6.0.2 on 2026-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_tareas/'),
        ),
    ]
